spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artvu
    username: artvu
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  cors:
    allowed-headers: '*'
    max-age: 3600
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-origins: '*'

springdoc:
  show-login-endpoint: true

logging:
  file:
    name: service.log
  logback:
    rollingpolicy:
      file-name-pattern: service.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10KB
  pattern:
    dateformat: Asia/Seoul