spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.100.30.52:23306/dartvu
    username: appartvu
    password: System01!!

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: embedded
  open-api:
    secretKey: "9bc5a206710943769d657e163212035d"

  cors:
    allowed-headers: '*'
    max-age: 3600
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-origins: '*'
springdoc:
  show-login-endpoint: true

logging:
  file:
    name: service.log
  logback:
    rolling policy:
      file-name-pattern: service.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10KB
  pattern:
    dateformat: Asia/Seoul
