spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.100.30.52:3306/dartvu
    username: appartvu
    password: System01!!

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true

springdoc:
  show-login-endpoint: true