spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    defer-datasource-initialization: true

cors:
  allowed-headers: '*'
  max-age: 3600
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-origins: '*'

logging:
  file:
    name: service.log
  logback:
    rollingpolicy:
      file-name-pattern: service.%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
  pattern:
    dateformat: Asia/Seoul

#운영에서 swagger 제공 안함
springdoc:
  api-docs:
    enabled: false
